name: WOD Automation

on:
  schedule:
    # Run daily at 8:00 AM UTC
    - cron: '0 8 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  process-wod:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py GitPython
          
          # Install your WOD CLI tool
          # Replace with the actual installation steps for your CLI tool
          # Example: pip install wod-cli
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Run Discord WOD Bot
        run: |
          uv run bot/discord_wod_bot.py \
            --token "${{ secrets.DISCORD_BOT_TOKEN }}" \
            --channel-id "${{ secrets.DISCORD_CHANNEL_ID }}" \
            --repo-path "." \
            --wod-path "wods" \
            --site-content-path "site/content/wods"
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
