name: WOD Automation

on:
  schedule:
    # Run at 6 PM Madrid time (UTC+2 in summer, UTC+1 in winter)
    # This cron expression is for 4 PM UTC (6 PM Madrid in winter)
    - cron: '0 16 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  process-wod:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Required to later push changes back to the repository
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.3"
          enable-cache: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Install wod CLI tool
        run: |
          cargo install --git https://github.com/plaguss/wod

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Run Discord WOD Bot
        run: |
          uv run bot/mchk_bot.py \
            --token "${{ secrets.DISCORD_BOT_TOKEN }}" \
            --channel-id "${{ secrets.DISCORD_CHANNEL_ID }}" \
            --repo-path "." \
            --wod-path "wods" \
            --site-content-path "site/content/wods"
